script:
- npm test
- npm run coverage-ci
language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: info@orangemug.co.uk
  api_key:
    secure: mQ5A0Co3zighB72eJyOTs1qBD3pywJp/54huZvcvmPH0H00r2dLG10l1MRBoEdBR2TrzFov4/sSXTFVJom7Q80Ca4VmMRyh+8v+o76W8qFpIkBjDeUCImmdRO6omDZk9QVw+CWHqqRb2Zn5IfzpMaQmhZcoYQ5wWWL5V5f4D7SJ9yG5gr3+darqIsT0AZxdLvF/NXJhoEJy65B9gdLpeuVdqZBpb2WgqPC2ner04w+43iTA2YeqEB320bK32g1nT8v0nBrJgbLOG0RPprG8NFUsjQFB+ZFH+VHf/YTtxmlIuLDN98KMvTh64KH+uO031QQF9DylMi4gxMgq8anPfoZpOqUDAkJx7oIpBZ5UpPemuJ1V9Ghj4a6dmKbyB+3KUIKqrDryKMYS8YtZRvBIn2O2Qp5xFamaN0qJDHn9AoKHcQLxdttaXef2i1vqk3aP+fiNgpbQcr7C6DxtV6MJfxGkV6Z6A4MhMV+xGCZ3V/59xdZeDgBgQEbZnqmEprSgYKnrGO4PAPHb+5Rp9/hdA69hzLHYeqgKOSwhw++5oQipjDMYJg6GiSWlppp0B8IQCclZ5p72FAogQeT24LFcfT/oFmmHKgnonnZupV/Es7MsfDVB1qAbyklcxSXtR5ozpR9kLnIVpFkTS7GpfXmWtrEJo8llyufphzHjIyL0jh6k=
  on:
    tags: true
env:
  global:
    secure: Rawhb3XgaB4W2+VpYw6il1EiC4cZjjS97I9ZYY6r/7KxTFZcXz6Ex8gbVCEoF2WHe/eFhXmxAUe2UZ/guAQx9JqF9nf8mrM3n2iNcuZdj9NScB+qyoGf0J+UmCtSipHRvC3pEnwnyvsCyBU7j5PykFPWDvj2plhCTf/PXPzHeKSOeGNkccrC6XW/k7+udMK5GJGXqsz6co5W2OgvjF3ZlXA4Z2Sx2YhTH1gZTXI2Q8SwKP+XfCUGPPRzn+IL5hWf/OL3D8no1GD8w6PsWUbruaAF+8CNnKqPm/qyxqTmTuIjLHw+vs3TG9+nEuu1PaaBXLRrk3EUFJEAOhTf0V9pNMF7OLBTPCum4mzyCD6i2N56A5c1zh4mlTgzw5nDpg91iIMUHL3REmYUqN1zvBFhXvKyA1LLm2OYFbbt6PD2KK0lMFj1G+RMXwtjfrVdp2wKvUeCOMbwF2/uFDdjzZ6kddMkjc/EO9mafyQCr4abAC/maMLYkOTfuVvsc9lgqDriPtnI9olI6+FieOfqXiFDSPaaNukUH7Abt9i934KgJyj/2FjJ+yAHEoIS6bYwWu9e5+pvXOmZhrj4dkJLsTS8dbypq6X5oGttOzekQRd4tEkXHK1PqAIFacly3ClmAPAKCOaZbtrB90IDzYpybEACttc71egE+dACSRbPIYbWqKw=
